services:
  mysqldb:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: co03190319
      MYSQL_DATABASE: cmm
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pco03190319"]
      interval: 5s
      timeout: 5s
      retries: 10

  spring:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8080:8080"

volumes:
  db-data:
